resources:
  - name: git
    icon: github
    type: git
    source:
      uri: https://github.com/shivanisarthi/mavenassignment
      branch: main
  - name: image
    type: docker-image
    icon: docker
    source:
      email: "shivani.sarthi@knoldus.com"
      username: "shivanisarthi123"
      password: "Shivani@123"
      repository: shivanisarthi123/concourse_ci_test

jobs:

  # This test job will fetch the source code from GitHub, and execute the test task.
  - name: compile
    plan:
      - get: git
        trigger: true # Trigger this job whenever Concourse detects a new Resource version (i.e. a new Git commit)
      - task: mvn-compile
        file: git/group2/compile.yml

  # This build job will fetch the source code,
  # then execute a 'build' task which is defined separately in the repository.
  - name: package
    plan:
      - get: git # Concourse is stateless and needs to be given an external input to this Job.
        passed:
          - compile # The 'unit' job must have passed for this job to execute
        trigger: true
      - task: mvn-package
        file: git/group2/package.yml
      # Take the image built in the previous task, and push it to our Docker registry Resource
      - put: hello-world-docker-image
        params:
          build: tutorial/tutorials/miscellaneous/docker-images/docker
